config/routes.rb
TenInNine::Application.routes.draw do
  root 'welcome#index'
  get 'about', to: 'welcome#about', as: 'about'

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create', as: 'session'  
  delete 'sessions/destroy', to: 'sessions#destroy', as: 'logout'

  resources :projects

  get 'tags/:tag', to: 'projects#index', as: :tag

  get 'users/:id', to: 'users#show', as: 'user' 
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, :github_url, :thumbnail_url, :presence => true
  acts_as_taggable
end

app/models/user.rb
class User < ActiveRecord::Base
  include SecureRandom

  has_secure_password
  before_save { self.token = create_hash}

  def create_hash
    token = SecureRandom.urlsafe_base64
    Digest::SHA1::hexdigest(token.to_s)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    token = cookies[:token]
    @current_user ||= token && User.find_by(token: token)
  end

  def current_user= (user)
    @current_user = user
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def destroy
    return hacker_please unless current_user
    
    Project.find(params[:id]).destroy
    
    flash.now[:project_deleted] = 'project successfully deleted'
    redirect_to current_user
  end

  def index
  if params[:tag]
    @projects = Project.tagged_with(params[:tag])
  else
    @projects = Project.all
  end
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    return hacker_please unless current_user

    @project = Project.new(project_params)

    if @project.save
      redirect_to current_user
    else
      flash[:incomplete] = "name, github, and description required"
      redirect_to new_project_path
    end
  end

  def update
    return hacker_please unless current_user

    @project = Project.find(params[:id])
    
    if @project.update_attributes(project_params)
      redirect_to current_user
    else
      render 'edit'
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  private
    def hacker_please
      flash[:hacker] = "dont hack me bro"
      redirect_to root_path
    end

    def project_params
      params.require(:project).permit(:name, :github_url, :thumbnail_url, :description, :tag_list)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_name(params[:session][:name])

    if user && user.authenticate(params[:session][:password])
      user.update_attributes(token: user.create_hash)
      cookies.permanent[:token] = user.token
      current_user = user

      redirect_to user_path user
    else
      flash.now[:signin] = 'try again'
      render 'new'
    end
  end

  def new
    user = User.find_by_token(cookies[:token])
    redirect_to user if user
  end

  def destroy
    current_user = nil
    cookies[:token] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController  
  def show 
    @projects =  Project.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="initial-scale=1.0">
  <title><%= yield :title %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link href="http://fonts.googleapis.com/css?family=Lato:400" rel="stylesheet" type="text/css">
  <%= csrf_meta_tags %>
</head>
<body class="body <%= yield :body_class %> clearfix">
  <% flash.each do |key, value| %>
    <div class="error <%= key %>"><%= value %></div>
  <% end %>

<%= yield %>

</body>
</html>

app/views/projects/edit.html.erb
<% provide(:title, 'Edit Project') %>
<h1>
  Edit this guy
</h1>
<%= form_for @project, :method => :patch do |proj| %>
  name: <%= proj.text_field :name %><br>
  github url: <%= proj.text_field :github_url %><br>
  thumbnail_url: <%= proj.text_field :thumbnail_url %><br>
  description: <%= proj.text_area :description %><br>
  tags: <%= proj.text_field :tag_list %><br><br>
  <%= proj.submit 'Edit'%>
<% end %>

app/views/projects/index.html.erb
<% provide(:title, 'Projects') %>
<%= javascript_include_tag "projects" %>
<% content_for(:body_class, 'projects') %>
  <section class="container">
    <h1 class="projects-title">Apps<br></h1>
    <% @projects.each do |project| %>
    <div class="project-container" data-id="<%= project.id %>">
      <h2 class="project-title"><%= project.name %></h2>
      <%= image_tag "#{project.thumbnail_url}", :class => "thumbnail" %>
      <h4 class="project-description"><%= project.description %></h4>
      <h3 class="project-tags">Tags: <% project.tag_list.each do |tag| %>
                                    <%= tag %>
                                   <% end %>
      </h3>
    </div>
    <% end %>
  </section>
  <%= render "shared/sidebar" %>
  <%= render "shared/about_link" %>
  <%= render "shared/tags" %>

app/views/projects/new.html.erb
<% provide(:title, 'New Project') %>
<h1>
  Create this guy
</h1>
<%= form_for @project do |proj| %>
  <%= proj.label :name %>:
  <%= proj.text_field :name %>
  <%= proj.label :github_url %>:
  <%= proj.text_field :github_url %>
  <%= proj.label :thumbnail_url %>:
  <%= proj.text_field :thumbnail_url %>
  <%= proj.label :description %>:
  <%= proj.text_area :description %>
  <%= proj.label :tag_list %>:
  <%= proj.text_field :tag_list %><br>
  <%= proj.submit 'create project'%>
<% end %>

app/views/projects/show.html.erb
<% provide(:title, 'App') %>
<% content_for(:body_class, 'show') %>
<section class="container">
  <h1 class="show-project-title">
    <%= @project.name %><br>
  </h1>
  <div class="show-project-container">
    <%= image_tag "#{@project.thumbnail_url}", :class => "show-thumbnail" %>
    <h3 class="source-code">
      <a href='<%= @project.github_url %>'>Check out Source Code</a>
    </h3>
    <h3 class="show-tags">
      Tags: <%= raw @project.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
    </h3>
    <p class="show-description">
      <%= @project.description %>
    </p>
  </div>
</section>
  <%= render "shared/sidebar" %>
  <%= render "shared/apps_link" %>
  <%= render "shared/tags" %>

app/views/projects/update.html.erb
<% provide(:title, 'Edit Project') %>
<h1>
  Edit this guy
</h1>
<%= form_for @project do |proj| %>
  name: <%= proj.text_field :name %><br>
  github url: <%= proj.text_field :github_url %><br>
  thumbnail_url: <%= proj.text_field :thumbnail_url %><br>
  description: <%= proj.text_area :description %><br><br>
  <%= proj.submit 'Edit'%>
<% end %>

app/views/shared/_about_link.html.erb
  <div class="apps-link-container">
    <h2 class="apps-link"><a href="/about">About</a></h2>
  </div>

app/views/shared/_apps_link.html.erb
  <div class="apps-link-container">
    <h2 class="apps-link"><a href="/projects">Apps</a></h2>
  </div>

app/views/shared/_sidebar.html.erb
<aside class="sidebar clearfix">
  <div class="intro">
    <%= image_tag "head_shot.jpeg", :class => "head-shot" %>
    <h2 class="by-line">Built by Jerry in Rochester NY</h2>
  </div>
  <div class="github info github-1">
    <a href="http://www.github.com/jvanstry">
      <%= image_tag "github.gif", :class => "github icon" %>
      <h3 class="github username">jvanstry</h3>
    </a>
  </div>
  <div class="twitter info twitter-1">
    <a href="http://www.twitter.com/jvanstry">
      <%= image_tag "twitter.png", :class => "twitter icon" %>
      <h3 class="twitter username">@jvanstry</h3>
    </a>
  </div>
</aside>

app/views/shared/_tags.html.erb
  <div class="tags-cotainer">
    <h2 class="tags-title">Tags</h2>
    <div class="tags" id="tag_cloud">
      <% tag_cloud Project.tag_counts, %w{s m l} do |tag, css_class| %>
        <%= link_to tag.name, tag_path(tag.name), class: css_class %>
      <% end %>
    </div>
  </div>

app/views/users/show.html.erb
<% provide(:title, 'Admin Panel') %>
<h1>
  Welcome to your wonderful admin panel Jer
</h1>
<h4>
  <%= link_to 'log out', logout_path, :method => :delete %>
</h4>
<div class='admin new-project'>
  <h2>
    <%= link_to 'new project', new_project_path, :method => :get %>
  </h2>
</div>
<h2>
  old projects
</h2>
<ul class='admin projects'>
  <% @projects.each do |proj| %>
    <li>
      <h3>  
        <%= link_to "#{proj.name}", project_path(proj), :method => :get %>
        <%= link_to 'edit project', edit_project_path(proj), :method => :get %>
        <%= link_to 'delete project', project_path(proj), :method => :delete %>
      </h3>
    </li>
    <br />
  <% end %>
</ul>

app/views/welcome/about.html.erb
<% provide(:title, 'About') %>
<% content_for(:body_class, 'about-page') %>
<section class="container">
  <h1 class="about-title">About<br></h1>
  <p class="about-text">I’ve been learning web development for about a year now and, in this time, I really haven’t built that many full-fledged apps from start to finish. Much of my time has been spent learning the basics of programming, reading about or watching videos on specific aspects of development, or reading code others have written. With “10 apps in 9 Weeks”, I am setting out to turn out an app a week, plus one app I will be working on the entire time, in an effort to see exactly what I’m capable of, see where my skills are actually at, and improve all aspects of my full-stack development skill set. It’s also going to be awesome to have a fun, comprehensive website to hang my hat on when people ask me what I can do and have been doing.</p>
</section>
<%= render "shared/sidebar" %>
<%= render "shared/apps_link" %>
<%= render "shared/tags" %>

app/views/welcome/index.html.erb
<% provide(:title, '10 apps, 9ish weeks') %>
<% content_for(:body_class, 'index') %>
<section class="container">
  <%= image_tag "10_in_9_logo.png", :class => "title" %>
  <div class="main"></div>
  <div class="buttons clearfix">
    <a href="/projects">
      <h1 class="apps">Apps</h1>
    </a>
    <a href="/about">
      <h1 class="about">About</h1>
    </a>
  </div>
  <footer class="_container clearfix">
    <%= image_tag "asterisk.png", :class => "asterisk" %>
    <h4 class="motto">an exercise in <del>suffering</del> learning</h4>
  </footer>
</section>
<%= render "shared/sidebar" %>